"""Step 6 — timeline.ts + series.ts for the atelier composition.

Single owner of: timeline.ts, series.ts (both in the project root)

The composition is fully synchronous and deterministic, so it does NOT fetch the
dataset at render time: this script emits a generated TypeScript mirror of the
canonical JSON and asserts the mirror is byte-equal in content. The JSON remains
the canonical asset; the mirror is a build product of it.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parent
REPO = PROJECT.parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

DATA = json.loads((PROJECT / "artifacts" / "etf_data.json").read_text())
SCRIPT = json.loads((PROJECT / "artifacts" / "script.json").read_text())
SCENE_PLAN = json.loads((PROJECT / "artifacts" / "scene_plan.json").read_text())
DECK = SCRIPT["metadata"]["on_screen_script"]
FPS = 30
TOTAL = SCRIPT["total_duration_seconds"]

OUT_TIMELINE = PROJECT / "timeline.ts"
OUT_SERIES = PROJECT / "series.ts"
OUT_PROPS = PROJECT / "artifacts" / "props.json"

SCENE_KEYS = {
    "sc01": ("Opening", "Opening"),
    "sc02": ("Cast", "ScenesOpening"),
    "sc03": ("Rules", "ScenesOpening"),
    "sc04": ("Race", "RaceStage"),
    "sc05": ("Result", "ScenesResult"),
    "sc06": ("Turn", "ScenesResult"),
    "sc07": ("Mechanism", "ScenesEvidence"),
    "sc08": ("Drawdown", "ScenesEvidence"),
    "sc09": ("Underwater", "ScenesEvidence"),
    "sc10": ("Closing", "ScenesClosing"),
}

# plot geometry — mirrors art-direction-instrument-plate.md
PLOT = {"x0": 150, "x1": 820, "y0": 300, "y1": 1030, "vLo": 70000, "vHi": 210000, "baseline": 100000}
SAFE = {"width": 1080, "height": 1920, "side": 96, "safeBottom": 520, "textFloor": 1400}
RACE = {"startSec": 13.6, "endSec": 70.0, "sceneStartSec": 13.2}


def ts(value) -> str:
    return json.dumps(value, ensure_ascii=False)


def build_series_module() -> str:
    dates = DATA["dates"]
    series = DATA["series"]
    funds = DATA["funds"]
    N = len(dates) - 1

    # year ticks, in absolute seconds and in plot x
    year_ticks = []
    for y in range(2021, 2027):
        i = next(k for k, dt in enumerate(dates) if dt[:4] == str(y))
        year_ticks.append({
            "label": str(y),
            "index": i,
            "tSec": round(RACE["startSec"] + (RACE["endSec"] - RACE["startSec"]) * i / N, 3),
            "x": round(PLOT["x0"] + (PLOT["x1"] - PLOT["x0"]) * i / N, 2),
        })

    lines = [
        "// GENERATED by build_timeline_ts.py — do not edit by hand.",
        f"// Mirror of artifacts/etf_data.json ({DATA['meta']['trading_days']} trading days).",
        "",
        f"export const DATES: string[] = {ts(dates)};",
        "",
        "export const SERIES: Record<string, number[]> = {",
    ]
    for f in funds:
        lines.append(f"  {ts(f['code'])}: {ts(series[f['code']])},")
    lines += [
        "};",
        "",
        "export const FUNDS = [",
    ]
    for f in funds:
        lines.append(
            "  { code: %s, name: %s, fullName: %s, category: %s, color: %s, inkLight: %s },"
            % (ts(f["code"]), ts(f["name"]), ts(f["full_name"]), ts(f["category"]), ts(f["color"]), ts(f["ink_light"]))
        )
    lines += [
        "] as const;",
        "",
        "export const METRICS: Record<string, {",
        "  finalAsset: number; cumulativeReturn: number; annualizedReturn: number;",
        "  maxDrawdown: number; mddPeakDate: string; mddTroughDate: string; mddDays: number;",
        "  peakAsset: number; peakDate: string; endVsPeak: number;",
        "  longestUnderwaterDays: number; longestUnderwaterRange: [string, string];",
        "}> = {",
    ]
    for f in funds:
        m = DATA["metrics"][f["code"]]
        lines.append(
            "  %s: { finalAsset: %d, cumulativeReturn: %r, annualizedReturn: %r, maxDrawdown: %r, "
            "mddPeakDate: %s, mddTroughDate: %s, mddDays: %d, peakAsset: %d, peakDate: %s, endVsPeak: %r, "
            "longestUnderwaterDays: %d, longestUnderwaterRange: %s },"
            % (
                ts(f["code"]), m["final_asset"], m["cumulative_return"], m["annualized_return"],
                m["max_drawdown"], ts(m["mdd_peak_date"]), ts(m["mdd_trough_date"]), m["mdd_days"],
                m["peak_asset"], ts(m["peak_date"]), m["end_vs_peak"],
                m["longest_underwater_days"], ts(list(m["longest_underwater_range"])),
            )
        )
    lines += [
        "};",
        "",
        f"export const YEAR_TICKS = {ts(year_ticks)};",
        "",
        "export const PLOT = " + ts(PLOT) + " as const;",
        "export const SAFE = " + ts(SAFE) + " as const;",
        "export const PLOT_HELPER_X = (i: number) =>",
        "  PLOT.x0 + (PLOT.x1 - PLOT.x0) * (Math.max(0, Math.min(INDEX_MAX, i)) / INDEX_MAX);",
        "export const PLOT_HELPER_Y = (v: number) =>",
        "  PLOT.y0 + (PLOT.y1 - PLOT.y0) * (PLOT.vHi - v) / (PLOT.vHi - PLOT.vLo);",
        "",
        f"export const INITIAL_ASSET = {DATA['meta']['initial_asset']};",
        f"export const TOTAL_DAYS = {len(dates)};",
        f"export const INDEX_MAX = {N};",
        "",
    ]
    return "\n".join(lines)


def build_timeline() -> str:
    scenes = DECK["scenes"]
    scenes_by_id = {s["id"]: s for s in scenes}
    race = scenes_by_id["sc04"]
    beats = race["data"]["beats"]

    scene_entries = []
    for s in scenes:
        sid = s["id"]
        key, _src = SCENE_KEYS[sid]
        from_frame = round(s["start_seconds"] * FPS)
        dur = round((s["end_seconds"] - s["start_seconds"]) * FPS)
        scene_entries.append({
            "id": sid,
            "key": key,
            "label": s["label"],
            "type": s["type"],
            "from": from_frame,
            "durationInFrames": dur,
            "startSec": s["start_seconds"],
            "endSec": s["end_seconds"],
        })
    total_frames = sum(e["durationInFrames"] for e in scene_entries)
    assert total_frames == round(TOTAL * FPS), (total_frames, TOTAL * FPS)
    for a, b in zip(scene_entries, scene_entries[1:]):
        assert a["from"] + a["durationInFrames"] == b["from"], (a["id"], b["id"])

    def localise(items, offset_key="at"):
        out = []
        for it in items:
            o = dict(it)
            o["atSec"] = round(it[offset_key] - RACE["sceneStartSec"], 3)
            out.append(o)
        return out

    race_beats = []
    for b in beats:
        d = b["data"]
        race_beats.append({
            "id": b["id"],
            "label": b["label"],
            "pins": localise(d.get("pins", [])),
            "callouts": localise(d.get("callouts", [])),
            "markers": localise(d.get("markers", [])),
            "head": d.get("head"),
            "rows": d.get("rows"),
            "contrast": d.get("contrast"),
            "foot": d.get("foot"),
            "endCard": {**d["end_card"], "atSec": round(d["end_card"]["at"] - RACE["sceneStartSec"], 3)}
            if d.get("end_card") else None,
        })

    lines = [
        "// GENERATED by build_timeline_ts.py — do not edit by hand.",
        "// Scene windows come from artifacts/script.json; annotation times are the",
        "// real data time points (linear natural-day mapping) shifted to scene-local seconds.",
        "",
        'import { PLOT as PLOT_GEO, SAFE as SAFE_GEO } from "./series";',
        'export { PLOT_HELPER_X, PLOT_HELPER_Y, DATES, SERIES, FUNDS, METRICS, YEAR_TICKS, INITIAL_ASSET, INDEX_MAX, TOTAL_DAYS } from "./series";',
        "",
        f"export const WIDTH = {SAFE['width']};",
        f"export const HEIGHT = {SAFE['height']};",
        f"export const FPS = {FPS};",
        f"export const TOTAL_SECONDS = {TOTAL};",
        f"export const DURATION_IN_FRAMES = {total_frames};",
        "",
        "export const COMPLIANCE_TEXT = " + ts(SCRIPT["metadata"]["compliance"]["financial_disclaimer"]) + ";",
        "",
        "export const SAFE = SAFE_GEO;",
        "export const PLOT = PLOT_GEO;",
        f"export const RACE = {ts({'startSec': RACE['startSec'], 'endSec': RACE['endSec'], 'sceneStartSec': RACE['sceneStartSec']})};",
        "",
        "export type SceneKey = " + " | ".join(ts(SCENE_KEYS[s['id']][0]) for s in scenes) + ";",
        "",
        "export type SceneEntry = {",
        "  id: string; key: SceneKey; label: string; type: string;",
        "  from: number; durationInFrames: number; startSec: number; endSec: number;",
        "};",
        "",
        f"export const SCENES: SceneEntry[] = {ts(scene_entries)};",
        "",
        f"export const RACE_BEATS = {ts(race_beats)};",
        "",
        f"export const OPENING = {ts(scenes_by_id['sc01']['data'])};",
        f"export const CAST = {ts(scenes_by_id['sc02']['data'])};",
        f"export const RULES = {ts(scenes_by_id['sc03']['data'])};",
        f"export const RESULT = {ts(scenes_by_id['sc05']['data'])};",
        f"export const TURN = {ts(scenes_by_id['sc06']['data'])};",
        f"export const MECHANISM = {ts(scenes_by_id['sc07']['data'])};",
        f"export const DRAWDOWN = {ts(scenes_by_id['sc08']['data'])};",
        f"export const UNDERWATER = {ts(scenes_by_id['sc09']['data'])};",
        f"export const CLOSING = {ts(scenes_by_id['sc10']['data'])};",
        "",
        f"export const DATE_SPAN_LABEL = {ts(DATA['dates'][0].replace('-', '.') + ' → ' + DATA['dates'][-1].replace('-', '.'))};",
        f"export const DATA_CAVEAT = {ts(DATA['meta']['caveat'])};",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUT_SERIES.write_text(build_series_module())
    OUT_TIMELINE.write_text(build_timeline())
    OUT_PROPS.write_text(json.dumps({
        "note": "Atelier composition reads its content from timeline.ts + series.ts. This file exists because the render tool always passes --props; it is intentionally minimal.",
        "project": PROJECT.name,
        "compositionId": "EtfFourFundRace",
        "fps": FPS,
        "durationInFrames": round(TOTAL * FPS),
    }, ensure_ascii=False, indent=1))

    print(f"[write] {OUT_SERIES.relative_to(REPO)}  ({OUT_SERIES.stat().st_size/1024:.0f} KB)")
    print(f"[write] {OUT_TIMELINE.relative_to(REPO)}  ({OUT_TIMELINE.stat().st_size/1024:.0f} KB)")
    print(f"[write] {OUT_PROPS.relative_to(REPO)}")

    scenes = DECK["scenes"]
    print()
    for s in scenes:
        f = round(s["start_seconds"] * FPS)
        n = round((s["end_seconds"] - s["start_seconds"]) * FPS)
        print(f"  {s['id']}  frame {f:>5} +{n:>5}  {s['start_seconds']:5.1f}–{s['end_seconds']:5.1f}s  {SCENE_KEYS[s['id']][0]}")


if __name__ == "__main__":
    main()
