#!/usr/bin/env python3
"""Generate projects/<slug>/timeline.ts — the composition's single source of timing.

Also emits the scene inventory (bespoke-composition step 1.5) into metadata so the
reviewer can check scene distinctness.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
PID = "xiaosan-economics-03-opportunity-cost"
PROJ = ROOT / "projects" / PID
ART = PROJ / "artifacts"

plan = json.loads((ART / "scene_plan.json").read_text())
edit = json.loads((ART / "edit_decisions.json").read_text())
caps = json.loads((PROJ / "assets/captions.json").read_text())["captions"]

FPS = 30
TOTAL = plan["scenes"][-1]["end_seconds"]
DUR_FRAMES = round(TOTAL * FPS)

# Beats where the on-screen typography itself carries the spoken line, so a
# duplicated caption would read as amateurish doubling
# (skills/meta/bespoke-composition.md → "Captions vs on-screen text").
TYPE_CARRIES_LINE = {
    "不是",                              # sc12 大字就是这一拍
    "也不是",                            # sc14 大字就是这一拍
    "所以有机会成本不等于不应该做",       # sc16 朱红批注就是这一句
    "周末在家躺一天",                    # sc01 画面叠字
    "一分钱没花",                        # sc01 画面叠字
    "这一天你本来还能拿去干什么",         # sc05 整场的唯一主体就是这个问句
    "你最可能去做的那件事是什么",         # sc09 逐字打出的问句
    "为了它你放弃了什么",                # sc21 补全句
    "为了它我放弃了什么",                # sc22 结尾落点（s10 用「我」）
    "有时候不能只看它给了你什么",         # sc21 画面上的重句
    "有时候不能只看它给了你什么",         # sc21 画面上的重句
}

key_by_scene = {c["label"].split(" ")[0]: c["variant"] for c in edit["cuts"]}

# captions converted to scene-local seconds so scene reveals land on real words
cue_index = {}
for c in caps:
    cue_index.setdefault(c["section_id"], []).append(c)
sec_of_scene = {sc["id"]: sc["script_section_id"] for sc in plan["scenes"]}

scenes = []
for sc in plan["scenes"]:
    f = round(sc["start_seconds"] * FPS)
    t = round(sc["end_seconds"] * FPS)
    cues = []
    for c in cue_index.get(sec_of_scene[sc["id"]], []):
        if c["end_seconds"] <= sc["start_seconds"] + 1e-6:
            continue
        if c["start_seconds"] >= sc["end_seconds"] - 1e-6:
            continue
        cues.append({
            "text": c["text"],
            "start": round(max(0.0, c["start_seconds"] - sc["start_seconds"]), 3),
            "end": round(min(sc["end_seconds"] - sc["start_seconds"],
                             c["end_seconds"] - sc["start_seconds"]), 3),
        })
    scenes.append({
        "cues": cues,
        "id": sc["id"],
        "key": key_by_scene[sc["id"]],
        "type": sc["type"],
        "from": f,
        "durationInFrames": t - f,
        "startSeconds": round(sc["start_seconds"], 3),
        "endSeconds": round(sc["end_seconds"], 3),
    })

# integrity: frames must tile the whole timeline
acc = 0
for s in scenes:
    assert s["from"] == acc, f"frame gap at {s['id']}: {s['from']} != {acc}"
    assert s["durationInFrames"] > 0, f"non-positive frames {s['id']}"
    acc += s["durationInFrames"]
assert acc == DUR_FRAMES, f"{acc} != {DUR_FRAMES}"

cpts = []
for c in caps:
    f = round(c["start_seconds"] * FPS)
    t = round(c["end_seconds"] * FPS)
    if t <= f:
        t = f + 1
    cpts.append({
        "id": c["id"],
        "text": c["text"],
        "from": f,
        "durationInFrames": t - f,
        "startSeconds": round(c["start_seconds"], 3),
        "endSeconds": round(c["end_seconds"], 3),
        "typeCarriesLine": c["text"] in TYPE_CARRIES_LINE,
    })

DISC = "本视频仅作知识分享，不构成任何投资建议。市场有风险，投资需谨慎。"

ts = f"""// AUTO-GENERATED by build_timeline_ts.py — do not edit by hand.
// Source: artifacts/scene_plan.json + edit_decisions.json + assets/captions.json

export const FPS = {FPS};
export const DURATION_IN_FRAMES = {DUR_FRAMES};
export const TOTAL_SECONDS = {TOTAL};
export const WIDTH = 1080;
export const HEIGHT = 1920;
export const SUBTITLE_SAFE_BOTTOM_PX = 520;
export const SUBTITLE_SAFE_SIDE_PX = 96;
export const NARRATION =
  "{PID}/audio/narration-master-v1.wav";
export const COMPLIANCE_TEXT =
  "{DISC}";

export type SceneKey =
{chr(10).join(f'  | "{s["key"]}"' for s in scenes)};

export type SceneTiming = {{
  id: string;
  key: SceneKey;
  type: string;
  from: number;
  durationInFrames: number;
  startSeconds: number;
  endSeconds: number;
  /** 本场内的字幕时点，换算成场景局部秒数，用于让画面动效落在真实语音上 */
  cues: {{ text: string; start: number; end: number }}[];
}};

export type CaptionTiming = {{
  id: string;
  text: string;
  from: number;
  durationInFrames: number;
  startSeconds: number;
  endSeconds: number;
  typeCarriesLine: boolean;
}};

export const SCENES: SceneTiming[] = {json.dumps(scenes, ensure_ascii=False, indent=2)};

export const CAPTIONS: CaptionTiming[] = {json.dumps(cpts, ensure_ascii=False, indent=2)};
"""

(PROJ / "timeline.ts").write_text(ts, encoding="utf-8")
print(f"timeline.ts written | scenes={len(scenes)} | captions={len(cpts)} | frames={DUR_FRAMES} ({DUR_FRAMES/FPS:.3f}s)")
print(f"  caption suppression (type carries the line): {sum(1 for c in cpts if c['typeCarriesLine'])}")
