// AUTO-GENERATED by build_timeline_ts.py — do not edit by hand.
// Source: artifacts/scene_plan.json + edit_decisions.json + assets/captions.json

export const FPS = 30;
export const DURATION_IN_FRAMES = 6486;
export const TOTAL_SECONDS = 216.198;
export const WIDTH = 1080;
export const HEIGHT = 1920;
export const SUBTITLE_SAFE_BOTTOM_PX = 520;
export const SUBTITLE_SAFE_SIDE_PX = 96;
export const NARRATION =
  "xiaosan-economics-03-opportunity-cost/audio/narration-master-v1.wav";
export const COMPLIANCE_TEXT =
  "本视频仅作知识分享，不构成任何投资建议。市场有风险，投资需谨慎。";

export type SceneKey =
  | "RealLieIn"
  | "CostZeroHero"
  | "ZeroLedger"
  | "StrikeTheSpend"
  | "QuestionFork"
  | "FourHoursTitle"
  | "OptionCardsIn"
  | "MutualExclusion"
  | "AskTheOneThing"
  | "NameTheOpportunityCost"
  | "DefinitionCard"
  | "NotANegation"
  | "ExtinguishSum"
  | "MisreadCard"
  | "NoVerdictBalance"
  | "CostIsNotError"
  | "StrikeTheEquals"
  | "FreeCoffeeQueue"
  | "ThreeVsFive"
  | "BoundaryTerms"
  | "CompleteTheJudgment"
  | "ClosingQuestion";

export type SceneTiming = {
  id: string;
  key: SceneKey;
  type: string;
  from: number;
  durationInFrames: number;
  startSeconds: number;
  endSeconds: number;
  /** 本场内的字幕时点，换算成场景局部秒数，用于让画面动效落在真实语音上 */
  cues: { text: string; start: number; end: number }[];
};

export type CaptionTiming = {
  id: string;
  text: string;
  from: number;
  durationInFrames: number;
  startSeconds: number;
  endSeconds: number;
  typeCarriesLine: boolean;
};

export const SCENES: SceneTiming[] = [
  {
    "cues": [
      {
        "text": "周末在家躺一天",
        "start": 0.12,
        "end": 1.525
      },
      {
        "text": "一分钱没花",
        "start": 1.525,
        "end": 2.529
      },
      {
        "text": "这一天的成本是不是0",
        "start": 2.529,
        "end": 2.689
      }
    ],
    "id": "sc01",
    "key": "RealLieIn",
    "type": "broll",
    "from": 0,
    "durationInFrames": 81,
    "startSeconds": 0.0,
    "endSeconds": 2.689
  },
  {
    "cues": [
      {
        "text": "这一天的成本是不是0",
        "start": 0.0,
        "end": 1.847
      }
    ],
    "id": "sc02",
    "key": "CostZeroHero",
    "type": "text_card",
    "from": 81,
    "durationInFrames": 66,
    "startSeconds": 2.689,
    "endSeconds": 4.886
  },
  {
    "cues": [
      {
        "text": "按我们平时理解成本的方式",
        "start": 0.0,
        "end": 2.364
      },
      {
        "text": "好像确实是这样",
        "start": 2.364,
        "end": 3.743
      },
      {
        "text": "没买东西",
        "start": 3.743,
        "end": 4.531
      },
      {
        "text": "没打车",
        "start": 4.531,
        "end": 5.122
      },
      {
        "text": "没出去吃饭",
        "start": 5.122,
        "end": 6.107
      },
      {
        "text": "银行卡一分钱都没少",
        "start": 6.107,
        "end": 7.88
      },
      {
        "text": "怎么看都是0成本",
        "start": 7.88,
        "end": 9.456
      }
    ],
    "id": "sc03",
    "key": "ZeroLedger",
    "type": "animation",
    "from": 147,
    "durationInFrames": 319,
    "startSeconds": 4.886,
    "endSeconds": 15.542
  },
  {
    "cues": [
      {
        "text": "但经济学算成本",
        "start": 0.0,
        "end": 1.371
      },
      {
        "text": "有时候根本不只看你花了多少钱",
        "start": 1.371,
        "end": 4.114
      },
      {
        "text": "它还会问你一个问题",
        "start": 4.114,
        "end": 4.238
      }
    ],
    "id": "sc04",
    "key": "StrikeTheSpend",
    "type": "text_card",
    "from": 466,
    "durationInFrames": 127,
    "startSeconds": 15.542,
    "endSeconds": 19.78
  },
  {
    "cues": [
      {
        "text": "它还会问你一个问题",
        "start": 0.0,
        "end": 1.639
      },
      {
        "text": "这一天你本来还能拿去干什么",
        "start": 1.639,
        "end": 4.186
      }
    ],
    "id": "sc05",
    "key": "QuestionFork",
    "type": "diagram",
    "from": 593,
    "durationInFrames": 141,
    "startSeconds": 19.78,
    "endSeconds": 24.466
  },
  {
    "cues": [
      {
        "text": "比如这个周六下午你一共有4个小时",
        "start": 0.0,
        "end": 3.138
      },
      {
        "text": "你可以在家休息",
        "start": 3.138,
        "end": 4.511
      },
      {
        "text": "也可以拍一期视频",
        "start": 4.511,
        "end": 4.642
      }
    ],
    "id": "sc06",
    "key": "FourHoursTitle",
    "type": "text_card",
    "from": 734,
    "durationInFrames": 139,
    "startSeconds": 24.466,
    "endSeconds": 29.108
  },
  {
    "cues": [
      {
        "text": "也可以拍一期视频",
        "start": 0.0,
        "end": 1.438
      },
      {
        "text": "可以接一个兼职",
        "start": 1.438,
        "end": 2.811
      },
      {
        "text": "或者去健身",
        "start": 2.811,
        "end": 3.792
      },
      {
        "text": "问题是这4个小时你只能真正使用一次",
        "start": 3.792,
        "end": 6.349
      }
    ],
    "id": "sc07",
    "key": "OptionCardsIn",
    "type": "animation",
    "from": 873,
    "durationInFrames": 191,
    "startSeconds": 29.108,
    "endSeconds": 35.457
  },
  {
    "cues": [
      {
        "text": "问题是这4个小时你只能真正使用一次",
        "start": 0.0,
        "end": 0.777
      },
      {
        "text": "最后你决定什么都不干就在家休息",
        "start": 0.777,
        "end": 3.719
      },
      {
        "text": "从银行卡来看支出确实是0",
        "start": 3.719,
        "end": 6.073
      }
    ],
    "id": "sc08",
    "key": "MutualExclusion",
    "type": "animation",
    "from": 1064,
    "durationInFrames": 200,
    "startSeconds": 35.457,
    "endSeconds": 42.13
  },
  {
    "cues": [
      {
        "text": "但经济学会继续问",
        "start": 0.0,
        "end": 1.452
      },
      {
        "text": "如果你没有选择休息",
        "start": 1.452,
        "end": 3.084
      },
      {
        "text": "你最可能去做的那件事是什么",
        "start": 3.084,
        "end": 5.443
      },
      {
        "text": "假设你认真想了一下",
        "start": 5.443,
        "end": 6.556
      }
    ],
    "id": "sc09",
    "key": "AskTheOneThing",
    "type": "text_card",
    "from": 1264,
    "durationInFrames": 197,
    "startSeconds": 42.13,
    "endSeconds": 48.686
  },
  {
    "cues": [
      {
        "text": "假设你认真想了一下",
        "start": 0.0,
        "end": 0.52
      },
      {
        "text": "如果不休息你大概率会去接一个兼职",
        "start": 0.52,
        "end": 3.423
      },
      {
        "text": "那个兼职对你的净价值",
        "start": 3.423,
        "end": 5.238
      },
      {
        "text": "大概是500块钱",
        "start": 5.238,
        "end": 6.689
      },
      {
        "text": "那你选择休息的时候",
        "start": 6.689,
        "end": 8.322
      },
      {
        "text": "虽然没有真的掏出500块钱",
        "start": 8.322,
        "end": 9.904
      }
    ],
    "id": "sc10",
    "key": "NameTheOpportunityCost",
    "type": "animation",
    "from": 1461,
    "durationInFrames": 297,
    "startSeconds": 48.686,
    "endSeconds": 58.59
  },
  {
    "cues": [
      {
        "text": "虽然没有真的掏出500块钱",
        "start": 0.0,
        "end": 0.777
      },
      {
        "text": "但你确实放弃了一个价值大概500块钱的替代方案",
        "start": 0.777,
        "end": 4.95
      },
      {
        "text": "这就是机会成本",
        "start": 4.95,
        "end": 6.22
      }
    ],
    "id": "sc11",
    "key": "DefinitionCard",
    "type": "text_card",
    "from": 1758,
    "durationInFrames": 222,
    "startSeconds": 58.59,
    "endSeconds": 66.01
  },
  {
    "cues": [
      {
        "text": "不过这里有一个特别容易搞错的地方",
        "start": 0.0,
        "end": 3.451
      },
      {
        "text": "你还可以拍视频可以健身可以出去玩",
        "start": 3.451,
        "end": 6.901
      },
      {
        "text": "那这些是不是全部都要加起来",
        "start": 6.901,
        "end": 9.705
      },
      {
        "text": "不是",
        "start": 9.705,
        "end": 10.136
      },
      {
        "text": "因为就算你不休息",
        "start": 10.136,
        "end": 11.862
      },
      {
        "text": "你也不可能同时完整做完所有这些事情",
        "start": 11.862,
        "end": 11.985
      }
    ],
    "id": "sc12",
    "key": "NotANegation",
    "type": "text_card",
    "from": 1980,
    "durationInFrames": 360,
    "startSeconds": 66.01,
    "endSeconds": 77.995
  },
  {
    "cues": [
      {
        "text": "你也不可能同时完整做完所有这些事情",
        "start": 0.0,
        "end": 3.543
      },
      {
        "text": "机会成本通常关注的是",
        "start": 3.543,
        "end": 5.7
      },
      {
        "text": "你放弃掉的最佳替代方案",
        "start": 5.7,
        "end": 8.072
      },
      {
        "text": "也就是说你选择A真正付出的机会成本",
        "start": 8.072,
        "end": 11.738
      },
      {
        "text": "不是所有BCD全部加起来",
        "start": 11.738,
        "end": 14.326
      },
      {
        "text": "而是那些没有被选择的方案里",
        "start": 14.326,
        "end": 17.13
      },
      {
        "text": "对你最有价值的那个",
        "start": 17.13,
        "end": 19.071
      }
    ],
    "id": "sc13",
    "key": "ExtinguishSum",
    "type": "animation",
    "from": 2340,
    "durationInFrames": 608,
    "startSeconds": 77.995,
    "endSeconds": 98.266
  },
  {
    "cues": [
      {
        "text": "不过说到这里可能又会产生另一个误会",
        "start": 0.0,
        "end": 3.181
      },
      {
        "text": "既然休息的机会成本可能是500块钱",
        "start": 3.181,
        "end": 6.362
      },
      {
        "text": "那是不是说明我躺这4个小时就亏了500",
        "start": 6.362,
        "end": 9.918
      },
      {
        "text": "也不是",
        "start": 9.918,
        "end": 10.479
      },
      {
        "text": "机会成本告诉你的只是",
        "start": 10.479,
        "end": 12.235
      }
    ],
    "id": "sc14",
    "key": "MisreadCard",
    "type": "text_card",
    "from": 2948,
    "durationInFrames": 367,
    "startSeconds": 98.266,
    "endSeconds": 110.501
  },
  {
    "cues": [
      {
        "text": "机会成本告诉你的只是",
        "start": 0.0,
        "end": 0.116
      },
      {
        "text": "你为了现在这个选择放弃了什么",
        "start": 0.116,
        "end": 2.736
      },
      {
        "text": "它并没有替你决定",
        "start": 2.736,
        "end": 4.233
      },
      {
        "text": "这个选择到底对不对",
        "start": 4.233,
        "end": 5.917
      },
      {
        "text": "如果你这一周已经非常累",
        "start": 5.917,
        "end": 7.975
      },
      {
        "text": "你觉得休息4个小时带来的恢复",
        "start": 7.975,
        "end": 10.595
      },
      {
        "text": "比接那单兼职对你更重要",
        "start": 10.595,
        "end": 12.654
      },
      {
        "text": "那么休息完全可能就是更好的选择",
        "start": 12.654,
        "end": 14.623
      }
    ],
    "id": "sc15",
    "key": "NoVerdictBalance",
    "type": "diagram",
    "from": 3315,
    "durationInFrames": 439,
    "startSeconds": 110.501,
    "endSeconds": 125.124
  },
  {
    "cues": [
      {
        "text": "那么休息完全可能就是更好的选择",
        "start": 0.0,
        "end": 0.838
      },
      {
        "text": "所以有机会成本不等于不应该做",
        "start": 0.838,
        "end": 3.457
      },
      {
        "text": "睡觉有机会成本",
        "start": 3.457,
        "end": 4.767
      },
      {
        "text": "陪家人有机会成本",
        "start": 4.767,
        "end": 6.264
      },
      {
        "text": "学习有机会成本",
        "start": 6.264,
        "end": 7.574
      },
      {
        "text": "工作同样有机会成本",
        "start": 7.574,
        "end": 9.258
      },
      {
        "text": "只要你在做选择",
        "start": 9.258,
        "end": 10.568
      },
      {
        "text": "其他可能性就一定会被放弃",
        "start": 10.568,
        "end": 12.814
      }
    ],
    "id": "sc16",
    "key": "CostIsNotError",
    "type": "text_card",
    "from": 3754,
    "durationInFrames": 420,
    "startSeconds": 125.124,
    "endSeconds": 139.138
  },
  {
    "cues": [
      {
        "text": "而且机会成本也不意味着",
        "start": 0.0,
        "end": 2.399
      },
      {
        "text": "所有东西都必须换算成钱",
        "start": 2.399,
        "end": 4.798
      },
      {
        "text": "有些时候你放弃的是收入",
        "start": 4.798,
        "end": 7.198
      },
      {
        "text": "有些时候放弃的是时间",
        "start": 7.198,
        "end": 9.379
      },
      {
        "text": "有些时候是精力",
        "start": 9.379,
        "end": 10.905
      },
      {
        "text": "还有些时候是陪伴休息或者一次学习机会",
        "start": 10.905,
        "end": 14.831
      },
      {
        "text": "所以经济学里的成本",
        "start": 14.831,
        "end": 16.637
      }
    ],
    "id": "sc17",
    "key": "StrikeTheEquals",
    "type": "animation",
    "from": 4174,
    "durationInFrames": 499,
    "startSeconds": 139.138,
    "endSeconds": 155.775
  },
  {
    "cues": [
      {
        "text": "所以经济学里的成本",
        "start": 0.0,
        "end": 0.157
      },
      {
        "text": "其实比我们平时理解的花了多少钱要宽得多",
        "start": 0.157,
        "end": 4.301
      },
      {
        "text": "比如商场送一杯免费咖啡",
        "start": 4.301,
        "end": 6.701
      },
      {
        "text": "咖啡确实不要钱",
        "start": 6.701,
        "end": 8.227
      },
      {
        "text": "但如果你要排两个小时的队",
        "start": 8.227,
        "end": 10.845
      },
      {
        "text": "那两个小时并不是免费的",
        "start": 10.845,
        "end": 13.244
      },
      {
        "text": "所以免费不等于没有成本",
        "start": 13.244,
        "end": 15.643
      }
    ],
    "id": "sc18",
    "key": "FreeCoffeeQueue",
    "type": "broll",
    "from": 4673,
    "durationInFrames": 494,
    "startSeconds": 155.775,
    "endSeconds": 172.218
  },
  {
    "cues": [
      {
        "text": "投资里也是一样",
        "start": 0.0,
        "end": 1.314
      },
      {
        "text": "假设两个选择的风险流动性和其他限制都差不多",
        "start": 1.314,
        "end": 5.258
      },
      {
        "text": "A最后赚了3%",
        "start": 5.258,
        "end": 6.572
      },
      {
        "text": "B本来可以赚5%",
        "start": 6.572,
        "end": 8.074
      },
      {
        "text": "那从机会成本的角度",
        "start": 8.074,
        "end": 9.764
      },
      {
        "text": "你还会多问一句",
        "start": 9.764,
        "end": 10.133
      }
    ],
    "id": "sc19",
    "key": "ThreeVsFive",
    "type": "diagram",
    "from": 5167,
    "durationInFrames": 304,
    "startSeconds": 172.218,
    "endSeconds": 182.351
  },
  {
    "cues": [
      {
        "text": "你还会多问一句",
        "start": 0.0,
        "end": 0.946
      },
      {
        "text": "我为了选择A放弃了什么",
        "start": 0.946,
        "end": 3.011
      },
      {
        "text": "当然现实里的投资选择不会这么简单",
        "start": 3.011,
        "end": 6.016
      },
      {
        "text": "风险流动性和确定性往往都不同",
        "start": 6.016,
        "end": 8.644
      },
      {
        "text": "所以不能只拿最终收益率机械比较",
        "start": 8.644,
        "end": 11.375
      }
    ],
    "id": "sc20",
    "key": "BoundaryTerms",
    "type": "text_card",
    "from": 5471,
    "durationInFrames": 341,
    "startSeconds": 182.351,
    "endSeconds": 193.726
  },
  {
    "cues": [
      {
        "text": "所以不能只拿最终收益率机械比较",
        "start": 0.0,
        "end": 0.086
      },
      {
        "text": "但机会成本会提醒我们一件事",
        "start": 0.086,
        "end": 2.527
      },
      {
        "text": "判断一个选择",
        "start": 2.527,
        "end": 3.654
      },
      {
        "text": "有时候不能只看它给了你什么",
        "start": 3.654,
        "end": 6.095
      },
      {
        "text": "还要看",
        "start": 6.095,
        "end": 6.658
      },
      {
        "text": "为了它你放弃了什么",
        "start": 6.658,
        "end": 8.348
      }
    ],
    "id": "sc21",
    "key": "CompleteTheJudgment",
    "type": "animation",
    "from": 5812,
    "durationInFrames": 277,
    "startSeconds": 193.726,
    "endSeconds": 202.974
  },
  {
    "cues": [
      {
        "text": "所以下次再遇到一件免费的事情",
        "start": 0.0,
        "end": 2.467
      },
      {
        "text": "别急着只问",
        "start": 2.467,
        "end": 3.348
      },
      {
        "text": "我要花多少钱",
        "start": 3.348,
        "end": 4.405
      },
      {
        "text": "也可以多问一句",
        "start": 4.405,
        "end": 5.638
      },
      {
        "text": "为了它我放弃了什么",
        "start": 5.638,
        "end": 7.224
      }
    ],
    "id": "sc22",
    "key": "ClosingQuestion",
    "type": "text_card",
    "from": 6089,
    "durationInFrames": 397,
    "startSeconds": 202.974,
    "endSeconds": 216.198
  }
];

export const CAPTIONS: CaptionTiming[] = [
  {
    "id": "cap-s01-01",
    "text": "周末在家躺一天",
    "from": 4,
    "durationInFrames": 42,
    "startSeconds": 0.12,
    "endSeconds": 1.525,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s01-02",
    "text": "一分钱没花",
    "from": 46,
    "durationInFrames": 30,
    "startSeconds": 1.525,
    "endSeconds": 2.529,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s01-03",
    "text": "这一天的成本是不是0",
    "from": 76,
    "durationInFrames": 60,
    "startSeconds": 2.529,
    "endSeconds": 4.536,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-04",
    "text": "按我们平时理解成本的方式",
    "from": 147,
    "durationInFrames": 71,
    "startSeconds": 4.886,
    "endSeconds": 7.25,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-05",
    "text": "好像确实是这样",
    "from": 218,
    "durationInFrames": 41,
    "startSeconds": 7.25,
    "endSeconds": 8.629,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-06",
    "text": "没买东西",
    "from": 259,
    "durationInFrames": 24,
    "startSeconds": 8.629,
    "endSeconds": 9.417,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-07",
    "text": "没打车",
    "from": 283,
    "durationInFrames": 17,
    "startSeconds": 9.417,
    "endSeconds": 10.008,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-08",
    "text": "没出去吃饭",
    "from": 300,
    "durationInFrames": 30,
    "startSeconds": 10.008,
    "endSeconds": 10.993,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-09",
    "text": "银行卡一分钱都没少",
    "from": 330,
    "durationInFrames": 53,
    "startSeconds": 10.993,
    "endSeconds": 12.766,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s02-10",
    "text": "怎么看都是0成本",
    "from": 383,
    "durationInFrames": 47,
    "startSeconds": 12.766,
    "endSeconds": 14.342,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s03-11",
    "text": "但经济学算成本",
    "from": 466,
    "durationInFrames": 41,
    "startSeconds": 15.542,
    "endSeconds": 16.913,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s03-12",
    "text": "有时候根本不只看你花了多少钱",
    "from": 507,
    "durationInFrames": 83,
    "startSeconds": 16.913,
    "endSeconds": 19.656,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s03-13",
    "text": "它还会问你一个问题",
    "from": 590,
    "durationInFrames": 53,
    "startSeconds": 19.656,
    "endSeconds": 21.419,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s03-14",
    "text": "这一天你本来还能拿去干什么",
    "from": 643,
    "durationInFrames": 76,
    "startSeconds": 21.419,
    "endSeconds": 23.966,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s04-15",
    "text": "比如这个周六下午你一共有4个小时",
    "from": 734,
    "durationInFrames": 94,
    "startSeconds": 24.466,
    "endSeconds": 27.604,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-16",
    "text": "你可以在家休息",
    "from": 828,
    "durationInFrames": 41,
    "startSeconds": 27.604,
    "endSeconds": 28.977,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-17",
    "text": "也可以拍一期视频",
    "from": 869,
    "durationInFrames": 47,
    "startSeconds": 28.977,
    "endSeconds": 30.546,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-18",
    "text": "可以接一个兼职",
    "from": 916,
    "durationInFrames": 42,
    "startSeconds": 30.546,
    "endSeconds": 31.919,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-19",
    "text": "或者去健身",
    "from": 958,
    "durationInFrames": 29,
    "startSeconds": 31.919,
    "endSeconds": 32.9,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-20",
    "text": "问题是这4个小时你只能真正使用一次",
    "from": 987,
    "durationInFrames": 100,
    "startSeconds": 32.9,
    "endSeconds": 36.234,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-21",
    "text": "最后你决定什么都不干就在家休息",
    "from": 1087,
    "durationInFrames": 88,
    "startSeconds": 36.234,
    "endSeconds": 39.176,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s04-22",
    "text": "从银行卡来看支出确实是0",
    "from": 1175,
    "durationInFrames": 71,
    "startSeconds": 39.176,
    "endSeconds": 41.53,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-23",
    "text": "但经济学会继续问",
    "from": 1264,
    "durationInFrames": 43,
    "startSeconds": 42.13,
    "endSeconds": 43.582,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-24",
    "text": "如果你没有选择休息",
    "from": 1307,
    "durationInFrames": 49,
    "startSeconds": 43.582,
    "endSeconds": 45.214,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-25",
    "text": "你最可能去做的那件事是什么",
    "from": 1356,
    "durationInFrames": 71,
    "startSeconds": 45.214,
    "endSeconds": 47.573,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s05-26",
    "text": "假设你认真想了一下",
    "from": 1427,
    "durationInFrames": 49,
    "startSeconds": 47.573,
    "endSeconds": 49.206,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-27",
    "text": "如果不休息你大概率会去接一个兼职",
    "from": 1476,
    "durationInFrames": 87,
    "startSeconds": 49.206,
    "endSeconds": 52.109,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-28",
    "text": "那个兼职对你的净价值",
    "from": 1563,
    "durationInFrames": 55,
    "startSeconds": 52.109,
    "endSeconds": 53.924,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-29",
    "text": "大概是500块钱",
    "from": 1618,
    "durationInFrames": 43,
    "startSeconds": 53.924,
    "endSeconds": 55.375,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-30",
    "text": "那你选择休息的时候",
    "from": 1661,
    "durationInFrames": 49,
    "startSeconds": 55.375,
    "endSeconds": 57.008,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-31",
    "text": "虽然没有真的掏出500块钱",
    "from": 1710,
    "durationInFrames": 71,
    "startSeconds": 57.008,
    "endSeconds": 59.367,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-32",
    "text": "但你确实放弃了一个价值大概500块钱的替代方案",
    "from": 1781,
    "durationInFrames": 125,
    "startSeconds": 59.367,
    "endSeconds": 63.54,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s05-33",
    "text": "这就是机会成本",
    "from": 1906,
    "durationInFrames": 38,
    "startSeconds": 63.54,
    "endSeconds": 64.81,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-34",
    "text": "不过这里有一个特别容易搞错的地方",
    "from": 1980,
    "durationInFrames": 104,
    "startSeconds": 66.01,
    "endSeconds": 69.461,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-35",
    "text": "你还可以拍视频可以健身可以出去玩",
    "from": 2084,
    "durationInFrames": 103,
    "startSeconds": 69.461,
    "endSeconds": 72.911,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-36",
    "text": "那这些是不是全部都要加起来",
    "from": 2187,
    "durationInFrames": 84,
    "startSeconds": 72.911,
    "endSeconds": 75.715,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-37",
    "text": "不是",
    "from": 2271,
    "durationInFrames": 13,
    "startSeconds": 75.715,
    "endSeconds": 76.146,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s06-38",
    "text": "因为就算你不休息",
    "from": 2284,
    "durationInFrames": 52,
    "startSeconds": 76.146,
    "endSeconds": 77.872,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-39",
    "text": "你也不可能同时完整做完所有这些事情",
    "from": 2336,
    "durationInFrames": 110,
    "startSeconds": 77.872,
    "endSeconds": 81.538,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-40",
    "text": "机会成本通常关注的是",
    "from": 2446,
    "durationInFrames": 65,
    "startSeconds": 81.538,
    "endSeconds": 83.695,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-41",
    "text": "你放弃掉的最佳替代方案",
    "from": 2511,
    "durationInFrames": 71,
    "startSeconds": 83.695,
    "endSeconds": 86.067,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-42",
    "text": "也就是说你选择A真正付出的机会成本",
    "from": 2582,
    "durationInFrames": 110,
    "startSeconds": 86.067,
    "endSeconds": 89.733,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-43",
    "text": "不是所有BCD全部加起来",
    "from": 2692,
    "durationInFrames": 78,
    "startSeconds": 89.733,
    "endSeconds": 92.321,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-44",
    "text": "而是那些没有被选择的方案里",
    "from": 2770,
    "durationInFrames": 84,
    "startSeconds": 92.321,
    "endSeconds": 95.125,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s06-45",
    "text": "对你最有价值的那个",
    "from": 2854,
    "durationInFrames": 58,
    "startSeconds": 95.125,
    "endSeconds": 97.066,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-46",
    "text": "不过说到这里可能又会产生另一个误会",
    "from": 2948,
    "durationInFrames": 95,
    "startSeconds": 98.266,
    "endSeconds": 101.447,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-47",
    "text": "既然休息的机会成本可能是500块钱",
    "from": 3043,
    "durationInFrames": 96,
    "startSeconds": 101.447,
    "endSeconds": 104.628,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-48",
    "text": "那是不是说明我躺这4个小时就亏了500",
    "from": 3139,
    "durationInFrames": 107,
    "startSeconds": 104.628,
    "endSeconds": 108.184,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-49",
    "text": "也不是",
    "from": 3246,
    "durationInFrames": 16,
    "startSeconds": 108.184,
    "endSeconds": 108.745,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s07-50",
    "text": "机会成本告诉你的只是",
    "from": 3262,
    "durationInFrames": 57,
    "startSeconds": 108.745,
    "endSeconds": 110.617,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-51",
    "text": "你为了现在这个选择放弃了什么",
    "from": 3319,
    "durationInFrames": 78,
    "startSeconds": 110.617,
    "endSeconds": 113.237,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-52",
    "text": "它并没有替你决定",
    "from": 3397,
    "durationInFrames": 45,
    "startSeconds": 113.237,
    "endSeconds": 114.734,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-53",
    "text": "这个选择到底对不对",
    "from": 3442,
    "durationInFrames": 51,
    "startSeconds": 114.734,
    "endSeconds": 116.418,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-54",
    "text": "如果你这一周已经非常累",
    "from": 3493,
    "durationInFrames": 61,
    "startSeconds": 116.418,
    "endSeconds": 118.476,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-55",
    "text": "你觉得休息4个小时带来的恢复",
    "from": 3554,
    "durationInFrames": 79,
    "startSeconds": 118.476,
    "endSeconds": 121.096,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-56",
    "text": "比接那单兼职对你更重要",
    "from": 3633,
    "durationInFrames": 62,
    "startSeconds": 121.096,
    "endSeconds": 123.155,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-57",
    "text": "那么休息完全可能就是更好的选择",
    "from": 3695,
    "durationInFrames": 84,
    "startSeconds": 123.155,
    "endSeconds": 125.962,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-58",
    "text": "所以有机会成本不等于不应该做",
    "from": 3779,
    "durationInFrames": 78,
    "startSeconds": 125.962,
    "endSeconds": 128.581,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s07-59",
    "text": "睡觉有机会成本",
    "from": 3857,
    "durationInFrames": 40,
    "startSeconds": 128.581,
    "endSeconds": 129.891,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-60",
    "text": "陪家人有机会成本",
    "from": 3897,
    "durationInFrames": 45,
    "startSeconds": 129.891,
    "endSeconds": 131.388,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-61",
    "text": "学习有机会成本",
    "from": 3942,
    "durationInFrames": 39,
    "startSeconds": 131.388,
    "endSeconds": 132.698,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-62",
    "text": "工作同样有机会成本",
    "from": 3981,
    "durationInFrames": 50,
    "startSeconds": 132.698,
    "endSeconds": 134.382,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-63",
    "text": "只要你在做选择",
    "from": 4031,
    "durationInFrames": 40,
    "startSeconds": 134.382,
    "endSeconds": 135.692,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s07-64",
    "text": "其他可能性就一定会被放弃",
    "from": 4071,
    "durationInFrames": 67,
    "startSeconds": 135.692,
    "endSeconds": 137.938,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-65",
    "text": "而且机会成本也不意味着",
    "from": 4174,
    "durationInFrames": 72,
    "startSeconds": 139.138,
    "endSeconds": 141.537,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-66",
    "text": "所有东西都必须换算成钱",
    "from": 4246,
    "durationInFrames": 72,
    "startSeconds": 141.537,
    "endSeconds": 143.936,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-67",
    "text": "有些时候你放弃的是收入",
    "from": 4318,
    "durationInFrames": 72,
    "startSeconds": 143.936,
    "endSeconds": 146.336,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-68",
    "text": "有些时候放弃的是时间",
    "from": 4390,
    "durationInFrames": 66,
    "startSeconds": 146.336,
    "endSeconds": 148.517,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-69",
    "text": "有些时候是精力",
    "from": 4456,
    "durationInFrames": 45,
    "startSeconds": 148.517,
    "endSeconds": 150.043,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-70",
    "text": "还有些时候是陪伴休息或者一次学习机会",
    "from": 4501,
    "durationInFrames": 118,
    "startSeconds": 150.043,
    "endSeconds": 153.969,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-71",
    "text": "所以经济学里的成本",
    "from": 4619,
    "durationInFrames": 59,
    "startSeconds": 153.969,
    "endSeconds": 155.932,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-72",
    "text": "其实比我们平时理解的花了多少钱要宽得多",
    "from": 4678,
    "durationInFrames": 124,
    "startSeconds": 155.932,
    "endSeconds": 160.076,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-73",
    "text": "比如商场送一杯免费咖啡",
    "from": 4802,
    "durationInFrames": 72,
    "startSeconds": 160.076,
    "endSeconds": 162.476,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-74",
    "text": "咖啡确实不要钱",
    "from": 4874,
    "durationInFrames": 46,
    "startSeconds": 162.476,
    "endSeconds": 164.002,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-75",
    "text": "但如果你要排两个小时的队",
    "from": 4920,
    "durationInFrames": 79,
    "startSeconds": 164.002,
    "endSeconds": 166.62,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-76",
    "text": "那两个小时并不是免费的",
    "from": 4999,
    "durationInFrames": 72,
    "startSeconds": 166.62,
    "endSeconds": 169.019,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s08-77",
    "text": "所以免费不等于没有成本",
    "from": 5071,
    "durationInFrames": 72,
    "startSeconds": 169.019,
    "endSeconds": 171.418,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-78",
    "text": "投资里也是一样",
    "from": 5167,
    "durationInFrames": 39,
    "startSeconds": 172.218,
    "endSeconds": 173.532,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-79",
    "text": "假设两个选择的风险流动性和其他限制都差不多",
    "from": 5206,
    "durationInFrames": 118,
    "startSeconds": 173.532,
    "endSeconds": 177.476,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-80",
    "text": "A最后赚了3%",
    "from": 5324,
    "durationInFrames": 40,
    "startSeconds": 177.476,
    "endSeconds": 178.79,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-81",
    "text": "B本来可以赚5%",
    "from": 5364,
    "durationInFrames": 45,
    "startSeconds": 178.79,
    "endSeconds": 180.292,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-82",
    "text": "那从机会成本的角度",
    "from": 5409,
    "durationInFrames": 50,
    "startSeconds": 180.292,
    "endSeconds": 181.982,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-83",
    "text": "你还会多问一句",
    "from": 5459,
    "durationInFrames": 40,
    "startSeconds": 181.982,
    "endSeconds": 183.297,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-84",
    "text": "我为了选择A放弃了什么",
    "from": 5499,
    "durationInFrames": 62,
    "startSeconds": 183.297,
    "endSeconds": 185.362,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-85",
    "text": "当然现实里的投资选择不会这么简单",
    "from": 5561,
    "durationInFrames": 90,
    "startSeconds": 185.362,
    "endSeconds": 188.367,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-86",
    "text": "风险流动性和确定性往往都不同",
    "from": 5651,
    "durationInFrames": 79,
    "startSeconds": 188.367,
    "endSeconds": 190.995,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-87",
    "text": "所以不能只拿最终收益率机械比较",
    "from": 5730,
    "durationInFrames": 84,
    "startSeconds": 190.995,
    "endSeconds": 193.812,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-88",
    "text": "但机会成本会提醒我们一件事",
    "from": 5814,
    "durationInFrames": 74,
    "startSeconds": 193.812,
    "endSeconds": 196.253,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-89",
    "text": "判断一个选择",
    "from": 5888,
    "durationInFrames": 33,
    "startSeconds": 196.253,
    "endSeconds": 197.38,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-90",
    "text": "有时候不能只看它给了你什么",
    "from": 5921,
    "durationInFrames": 74,
    "startSeconds": 197.38,
    "endSeconds": 199.821,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s09-91",
    "text": "还要看",
    "from": 5995,
    "durationInFrames": 17,
    "startSeconds": 199.821,
    "endSeconds": 200.384,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s09-92",
    "text": "为了它你放弃了什么",
    "from": 6012,
    "durationInFrames": 50,
    "startSeconds": 200.384,
    "endSeconds": 202.074,
    "typeCarriesLine": true
  },
  {
    "id": "cap-s10-93",
    "text": "所以下次再遇到一件免费的事情",
    "from": 6089,
    "durationInFrames": 74,
    "startSeconds": 202.974,
    "endSeconds": 205.441,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s10-94",
    "text": "别急着只问",
    "from": 6163,
    "durationInFrames": 27,
    "startSeconds": 205.441,
    "endSeconds": 206.322,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s10-95",
    "text": "我要花多少钱",
    "from": 6190,
    "durationInFrames": 31,
    "startSeconds": 206.322,
    "endSeconds": 207.379,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s10-96",
    "text": "也可以多问一句",
    "from": 6221,
    "durationInFrames": 37,
    "startSeconds": 207.379,
    "endSeconds": 208.612,
    "typeCarriesLine": false
  },
  {
    "id": "cap-s10-97",
    "text": "为了它我放弃了什么",
    "from": 6258,
    "durationInFrames": 48,
    "startSeconds": 208.612,
    "endSeconds": 210.198,
    "typeCarriesLine": true
  }
];
