import React from 'react';
import {AbsoluteFill, Composition, Img, staticFile, useCurrentFrame} from 'remotion';

const C={bg:'#11100E',paper:'#F1EBDD',gold:'#C9A45C',teal:'#5E9C93',red:'#B45A45',graph:'#292723',gray:'#9C978D'};
const font="PingFang SC, Noto Sans CJK SC, Arial, sans-serif";

const scenes=[
 ['反弹之后，问题才开始','黄金又反弹了'],['四种选择，同一个名字','金条｜积存金｜黄金ETF｜黄金股'],['黄金涨 10%','它们都会涨 10% 吗？'],['先看你买到什么权利','实物｜账户｜基金｜股权'],['入口相似，底层权利不同','四种资产形态'],['积存金不是普通存款','本金固定？｜随金价变化'],['便利背后还有规则','手续费｜兑换｜门槛'],['前三种更接近黄金本身','黄金股是公司股权'],['黄金股背后是一家公司','公司经营'],['利润由多种变量共同决定','产量｜能源｜人工｜品位｜债务｜估值'],['实验一：成本不变','售价 100→110｜利润 20→30'],['金价 +10%','单位利润 +50%'],['实验二：成本上升','成本 80→100｜利润只剩 10'],['方向甚至可能相反','金价只是利润的一项变量'],['先把三组数据放到同一张表','共同交易日｜不填补缺失日'],['再把起点统一为 100','Gold｜GLD｜GDX'],['历史阶段 A','2016-01-19—2016-06-17'],['同一阶段的终点变化','黄金 +19.38%｜GLD +19.21%｜GDX +106.82%'],['历史阶段 B','2017-01-05—2017-06-01'],['另一种分叉','黄金 +7.10%｜GLD +7.23%｜GDX -2.59%'],['再看一次下跌有多深','最大回撤'],['矿业股这一路更颠簸','Gold -5.54%｜GLD -5.52%｜GDX -17.48%'],['报价不动，也可能先亏费用','买入费 + 赎回费'],['刚买再卖，约先少 1%','机制示意｜规则以银行最新为准'],['实物回购先看类别与验金','称重｜成色｜检测'],['同是黄金，参考回购会分档','不同类别存在差异'],['四种工具，四类偏离源','溢价｜规则｜跟踪｜经营'],['结论','不会自动同涨 10%'],['以后先问这四个问题','权利｜收益｜成本｜偏离'],['研究边界','历史展示 ≠ 未来预测'],['本视频仅作知识分享，不构成任何投资建议。','市场有风险，投资需谨慎。'],
] as const;

const base:React.CSSProperties={fontFamily:font,color:C.paper};
const line=(pts:string,color=C.gold,w=10)=><polyline points={pts} fill="none" stroke={color} strokeWidth={w} strokeLinecap="round" strokeLinejoin="round"/>;
const Axis=()=> <svg viewBox="0 0 900 600" style={{width:'100%'}}><path d="M90 40V520H830" stroke={C.gray} strokeWidth="4" opacity=".55"/>{[0,1,2,3].map(i=><path key={i} d={`M90 ${120+i*110}H830`} stroke={C.gray} strokeWidth="2" opacity=".16"/>)}</svg>;
const Pill=({children,color=C.gold}:{children:React.ReactNode;color?:string})=><div style={{border:`2px solid ${color}`,borderRadius:999,padding:'15px 25px',fontSize:28,color,whiteSpace:'nowrap'}}>{children}</div>;
const Stamp=({children}:{children:React.ReactNode})=><div style={{border:`4px double ${C.gold}`,color:C.gold,padding:'18px 24px',fontWeight:800,fontSize:34,transform:'rotate(-2deg)',background:'#11100Ecc'}}>{children}</div>;
const Paper=({children}:{children:React.ReactNode})=><div style={{background:C.paper,color:C.bg,borderRadius:6,padding:48,boxShadow:'0 22px 70px #0008',width:'84%',minHeight:720,position:'relative',overflow:'hidden'}}>{children}<div style={{position:'absolute',inset:0,opacity:.06,backgroundImage:'repeating-linear-gradient(0deg,#000 0,#000 1px,transparent 1px,transparent 7px)',pointerEvents:'none'}}/></div>;
const Bars=({vals,labels,colors}:{vals:number[];labels:string[];colors?:string[]})=><div style={{display:'flex',alignItems:'flex-end',gap:35,height:610,width:'82%',borderBottom:`3px solid ${C.gray}`}}>{vals.map((v,i)=><div key={labels[i]} style={{flex:1,textAlign:'center'}}><div style={{height:v,background:colors?.[i]||C.gold,borderRadius:'8px 8px 0 0',display:'flex',alignItems:'flex-start',justifyContent:'center',paddingTop:20,color:C.bg,fontWeight:900,fontSize:28}}>{labels[i].split('|')[1]}</div><div style={{marginTop:18,fontSize:27}}>{labels[i].split('|')[0]}</div></div>)}</div>;

const Visual=({id}:{id:number})=>{
 const four=['金条','积存金','黄金 ETF','黄金股'];
 if(id===1)return <div style={{position:'relative',width:'88%'}}><Axis/><svg viewBox="0 0 900 600" style={{position:'absolute',inset:0,width:'100%'}}>{line('90,470 190,450 290,480 390,370 500,390 610,250 720,210 820,120')}</svg><Stamp>黄金又反弹了</Stamp></div>;
 if(id===2)return <div style={{display:'grid',gap:24,width:'82%'}}>{four.map((x,i)=><div key={x} style={{background:i===3?C.graph:C.paper,color:i===3?C.paper:C.bg,padding:'27px 36px',fontSize:40,borderLeft:`12px solid ${i===3?C.teal:C.gold}`}}>{String(i+1).padStart(2,'0')}　{x}</div>)}</div>;
 if(id===3)return <div style={{textAlign:'center'}}><div style={{fontSize:170,fontWeight:900,color:C.gold}}>+10%</div><div style={{fontSize:62,fontWeight:800}}>都会一样吗？</div><div style={{display:'flex',gap:15,marginTop:70}}>{four.map(x=><Pill key={x}>{x}</Pill>)}</div></div>;
 if(id===4)return <Paper><div style={{borderLeft:`5px solid ${C.gold}`,paddingLeft:38,display:'grid',gap:35}}>{[['金条','实物所有权'],['积存金','银行账户份额'],['黄金ETF','基金份额'],['黄金股','公司股权']].map(x=><div><small style={{color:C.gray,fontSize:25}}>{x[0]}</small><div style={{fontSize:44,fontWeight:800}}>{x[1]}</div></div>)}</div></Paper>;
 if(id===5)return <div style={{width:'88%',display:'grid',gridTemplateColumns:'1fr 1fr',gap:30}}>{four.map((x,i)=><div style={{height:280,border:`3px solid ${i===3?C.teal:C.gold}`,display:'grid',placeItems:'center',fontSize:40,background:C.graph}}>{x}<div style={{fontSize:24,color:C.gray}}>{['金属','账户','基金','股权'][i]}</div></div>)}</div>;
 if(id===6)return <div style={{display:'flex',gap:30,width:'88%'}}>{[['普通存款',false],['积存金',true]].map(([x,w]:any)=><div style={{flex:1,background:C.paper,color:C.bg,padding:35}}><h2>{x}</h2><svg viewBox="0 0 350 420">{line(w?'20,250 90,180 160,280 230,120 330,205':'20,220 330,220',w?C.gold:C.gray,8)}</svg><b>{w?'随金价变化':'本金路径较稳定'}</b></div>)}</div>;
 if(id===7)return <Paper><div style={{fontSize:42,fontWeight:900}}>积存金账户</div><div style={{height:40,background:C.gold,width:'72%',margin:'60px 0'}}/><div style={{display:'flex',gap:18}}>{['手续费','兑换','门槛'].map(x=><Pill>{x}</Pill>)}</div><p style={{marginTop:90,color:C.gray}}>以银行最新规则为准</p></Paper>;
 if(id===8)return <div style={{width:'88%',textAlign:'center'}}><div style={{display:'flex',justifyContent:'center',gap:18}}>{four.slice(0,3).map(x=><Pill>{x}</Pill>)}</div><div style={{height:180,borderLeft:`5px solid ${C.gold}`,marginLeft:'50%'}}/><div style={{display:'flex',justifyContent:'space-around'}}><Stamp>黄金本身</Stamp><div style={{borderTop:`5px solid ${C.teal}`,paddingTop:20,fontSize:36}}>黄金股 → 公司经营</div></div></div>;
 if(id===9||id===25)return <div style={{width:'100%',height:'100%',position:'relative'}}><Img src={staticFile(id===9?'review/sc09.jpg':'review/sc25.jpg')} style={{width:'100%',height:'100%',objectFit:'cover',filter:'brightness(.72) saturate(.75)'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(transparent 42%,#11100Edd 78%)'}}/><div style={{position:'absolute',left:70,bottom:120}}><Stamp>{id===9?'公司经营':'实物回购要看类别与验金'}</Stamp></div></div>;
 if(id===10)return <div style={{position:'relative',width:800,height:800,display:'grid',placeItems:'center'}}><div style={{width:220,height:220,borderRadius:'50%',border:`8px solid ${C.gold}`,display:'grid',placeItems:'center',fontSize:42,fontWeight:800}}>利润</div>{['产量','能源','人工','品位','债务','估值'].map((x,i)=><div style={{position:'absolute',left:330+300*Math.cos(i*Math.PI/3),top:330+300*Math.sin(i*Math.PI/3)}}><Pill color={i%2?C.teal:C.gold}>{x}</Pill></div>)}</div>;
 if(id===11)return <Bars vals={[530,410,120]} labels={['售价|110','成本|80','利润|30']} colors={[C.paper,C.red,C.gold]}/>;
 if(id===12)return <div style={{display:'flex',gap:55,alignItems:'center'}}><div style={{fontSize:86,fontWeight:900}}>金价<br/><b style={{color:C.gold}}>+10%</b></div><div style={{fontSize:90,color:C.gray}}>→</div><div style={{fontSize:86,fontWeight:900}}>利润<br/><b style={{color:C.gold}}>+50%</b></div></div>;
 if(id===13)return <Bars vals={[530,485,45]} labels={['售价|110','成本|100','利润|10']} colors={[C.paper,C.red,C.gold]}/>;
 if(id===14)return <div style={{display:'grid',gridTemplateColumns:'1fr auto 1fr',alignItems:'center',gap:30}}><Stamp>金价 ↑</Stamp><div style={{fontSize:90,color:C.red}}>＋成本 ↑</div><Stamp>利润 ↓</Stamp></div>;
 if(id===15)return <div style={{width:'84%',display:'grid',gap:40}}>{['Gold 现货','GLD','GDX'].map((x,i)=><div style={{display:'flex',alignItems:'center',gap:25}}><Pill color={[C.gold,C.paper,C.teal][i]}>{x}</Pill><div style={{height:5,background:[C.gold,C.paper,C.teal][i],flex:1}}/><Stamp>共同交易日</Stamp></div>)}</div>;
 if(id===16)return <div style={{width:'84%'}}><div style={{fontSize:150,fontWeight:900,color:C.gold,textAlign:'center'}}>100</div><div style={{display:'flex',justifyContent:'space-between',borderTop:`4px solid ${C.gray}`,paddingTop:35}}>{['Gold','GLD','GDX'].map((x,i)=><Pill color={[C.gold,C.paper,C.teal][i]}>{x}</Pill>)}</div></div>;
 if(id===17||id===19)return <div style={{position:'relative',width:'88%'}}><Axis/><svg viewBox="0 0 900 600" style={{position:'absolute',inset:0,width:'100%'}}>{line(id===17?'90,430 220,400 350,370 480,300 620,250 820,210':'90,390 220,370 350,390 480,330 620,350 820,320',C.gold,7)}{line(id===17?'90,440 220,410 350,380 480,305 620,255 820,215':'90,400 220,375 350,395 480,335 620,355 820,315',C.paper,7)}{line(id===17?'90,450 220,380 350,260 480,190 620,120 820,55':'90,410 220,380 350,430 480,470 620,440 820,455',C.teal,9)}</svg></div>;
 if(id===18)return <Bars vals={[120,118,590]} labels={['黄金|+19.38%','GLD|+19.21%','GDX|+106.82%']} colors={[C.gold,C.paper,C.teal]}/>;
 if(id===20)return <Bars vals={[250,255,70]} labels={['黄金|+7.10%','GLD|+7.23%','GDX|-2.59%']} colors={[C.gold,C.paper,C.red]}/>;
 if(id===21)return <div style={{width:'80%',height:760,position:'relative'}}><div style={{position:'absolute',left:80,top:80,right:120,borderTop:`8px solid ${C.gold}`}}/><div style={{position:'absolute',right:120,top:80,height:500,borderRight:`8px solid ${C.red}`}}/><div style={{position:'absolute',right:70,top:280,fontSize:42,color:C.red}}>最大回撤</div><svg viewBox="0 0 800 700">{line('80,80 190,160 310,110 440,270 560,240 680,580',C.paper,10)}</svg></div>;
 if(id===22)return <Bars vals={[190,188,600]} labels={['Gold|-5.54%','GLD|-5.52%','GDX|-17.48%']} colors={[C.gold,C.paper,C.red]}/>;
 if(id===23)return <div style={{display:'flex',alignItems:'center',gap:24,width:'88%'}}><div style={{height:105,width:250,background:C.gold,color:C.bg,display:'grid',placeItems:'center',fontSize:35,fontWeight:900}}>100 份价值</div>{['买入费','赎回费'].map(x=><><div style={{fontSize:65}}>→</div><div style={{width:120,height:260,border:`8px solid ${C.red}`,display:'grid',placeItems:'center',fontSize:27,writingMode:'vertical-rl'}}>{x}</div></>)}</div>;
 if(id===24)return <div style={{textAlign:'center'}}><div style={{fontSize:36,color:C.gray}}>报价保持不变</div><div style={{fontSize:180,fontWeight:900,color:C.red,margin:'60px 0'}}>约 -1%</div><Stamp>双边费用机制示意</Stamp></div>;
 if(id===26)return <Paper><div style={{fontSize:35,color:C.gray}}>工行参考回购分类</div><div style={{marginTop:70,display:'grid',gap:38}}>{['品牌金','其他 Au99 及以上黄金'].map((x,i)=><div><b style={{fontSize:38}}>{x}</b><div style={{height:24,width:i?'69%':'76%',background:i?C.teal:C.gold,marginTop:16}}/></div>)}</div><p style={{marginTop:90}}>不同类别的参考回购存在差异</p></Paper>;
 if(id===27)return <div style={{width:'88%',display:'grid',gap:24}}>{[['金条','溢价 / 回购'],['积存金','费用 / 规则'],['黄金ETF','费用 / 跟踪'],['黄金股','经营 / 估值']].map((x,i)=><div style={{display:'grid',gridTemplateColumns:'1fr 1.5fr',alignItems:'center',borderBottom:`2px solid ${C.graph}`,padding:20}}><b style={{fontSize:34}}>{x[0]}</b><div style={{height:55,background:[C.gold,C.paper,C.teal,C.red][i],color:C.bg,padding:'10px 20px',fontSize:28}}>{x[1]}</div></div>)}</div>;
 if(id===28)return <div style={{textAlign:'center'}}><div style={{fontSize:56}}>不会自动</div><div style={{fontSize:140,fontWeight:900,color:C.gold}}>同涨 10%</div><div style={{height:8,background:C.red,transform:'rotate(-3deg)',marginTop:-70}}/></div>;
 if(id===29)return <Paper><div style={{fontSize:32,color:C.gray,marginBottom:40}}>黄金产品检验单</div>{['买到什么权利？','收益来自哪里？','完整成本是什么？','何时偏离金价？'].map((x,i)=><div style={{fontSize:41,fontWeight:800,padding:'27px 0',borderBottom:`2px solid ${C.gray}`}}><span style={{color:C.gold,marginRight:25}}>0{i+1}</span>{x}</div>)}</Paper>;
 if(id===30)return <div style={{width:'88%',display:'grid',gridTemplateColumns:'1fr 1fr',gap:30}}><Paper><div style={{fontSize:34}}>历史证据</div><svg viewBox="0 0 500 500">{line('20,400 110,300 210,340 310,180 460,120',C.gold,10)}</svg><Stamp>已发生</Stamp></Paper><div style={{border:`3px dashed ${C.gray}`,display:'grid',placeItems:'center',fontSize:80,color:C.gray}}>未来<br/>…</div></div>;
 return <div style={{width:'86%',padding:'80px 55px',borderTop:`5px solid ${C.gold}`,borderBottom:`5px solid ${C.gold}`,textAlign:'center'}}><div style={{fontSize:55,fontWeight:800,lineHeight:1.55}}>本视频仅作知识分享，<br/>不构成任何投资建议。</div><div style={{fontSize:42,color:C.gold,marginTop:55}}>市场有风险，投资需谨慎。</div></div>;
};

export const ReviewFilmstrip=()=>{
 const frame=useCurrentFrame(); const idx=Math.max(0,Math.min(30,frame)); const [title,sub]=scenes[idx];
 return <AbsoluteFill style={{...base,background:C.bg,overflow:'hidden'}}>
  <div style={{position:'absolute',inset:0,opacity:.035,backgroundImage:'repeating-linear-gradient(0deg,#fff 0,#fff 1px,transparent 1px,transparent 8px)'}}/>
  {idx+1!==9&&idx+1!==25&&<><div style={{position:'absolute',left:70,top:75,fontSize:24,letterSpacing:5,color:C.gray}}>GOLD / ASSAY NOTE　{String(idx+1).padStart(2,'0')}</div><div style={{position:'absolute',left:70,right:70,top:135,borderTop:`2px solid ${C.graph}`}}/></>}
  <div style={{position:'absolute',inset:'175px 0 380px',display:'grid',placeItems:'center'}}><Visual id={idx+1}/></div>
  {idx+1!==31&&<div style={{position:'absolute',left:70,right:70,bottom:90}}><div style={{fontSize:53,fontWeight:850,lineHeight:1.12,maxWidth:900}}>{title}</div><div style={{fontSize:27,color:C.gold,marginTop:23,letterSpacing:1}}>{sub}</div></div>}
 </AbsoluteFill>;
};

export const HuangjinReviewRoot=()=> <Composition id="HuangjinReview" component={ReviewFilmstrip} durationInFrames={31} fps={30} width={1080} height={1920}/>;
